yarn upgrade --latest (minus a few).
I did not upgrade these due to API changes:
* MUI
* geolib
* react-jss
* @date-io/dayjs https://material-ui-pickers.dev/getting-started/installation#peer-library

I added `babel-polyfill` to fix this:
> ReferenceError: regeneratorRuntime is not defined
>     at <Jasmine>
>     at _ref2 (spec/karma_spec_index.js:65107:3)
>     at webpack:///src/lib/climate/daymetClient/index.js:20:1 <- spec/karma_spec_index.js:65101:16
>     at UserContext.<anonymous> (webpack:///spec/lib/climate/daymetClient/indexSpec.js:22:35 <- spec/karma_spec_index.js:63836:103)
>     at <Jasmine>

https://stackoverflow.com/a/34195553/7186678